version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "⬆️ deps:"
    open-pull-requests-limit: 10
